### ISSUE TITLE
[《C#8.0和.NET Core 3.0高级编程》](https://book.douban.com/subject/35249961/)

### ISSUE THREAD

**Issue by gaohuan9512** [YSGStudyHards/DotNetGuide#13]
[《C#8.0和.NET Core 3.0高级编程》](https://book.douban.com/subject/35249961/)

> 在《C#8.0和.NET Core 3.0高级编程》中,专家级作家Mark J. Price提供了开始编写C#应用程序所需的一切技能,适用于所有主流操作系统。 使用当前最流行的Visual Studio Code编辑器开展编程任务，对上一版内容进行了全面的更新和扩展，新增了两章专门介绍内容管理系统(CMS)以及如何使用ML.NET进行机器学习。包含C#编程的所有主题,可分为三大部分，第一大部分介绍C#基础知识,包括面向对象编程以及新的C#8.0特性,比如可空引用类型、简化的switch模式匹配以及默认的接口方法。第二大部分介绍.NETStandard APl，包括管理和查询数据、监视和改进性能以及使用文件系统、异步流、序列化和加密等。第三大部分介绍如何构建和部署跨平台的应用程序，例如使用ASP.NET Core构建Web应用程序和使用Xamarin.Forms构建移动应用程序。还介绍了构建Windows桌面应用程序的三种技术——Windows Forms.WPF(WindowsPresentation Foundation)和UWP(UniversalWindows Platform)。

_Originally posted by @YSGStudyHards in https://github.com/YSGStudyHards/DotNetGuide/issues/9#issuecomment-751250261_

**Comment by YSGStudyHards** [comment]
你好，该书已经在[C#/.NET/.NET Core推荐学习书籍 ](https://github.com/YSGStudyHards/DotNetGuide/issues/9)中收集，假如你还要好的书籍推荐并且在这个Issues中没有提及的可以在该[C#/.NET/.NET Core推荐学习书籍 ](https://github.com/YSGStudyHards/DotNetGuide/issues/9)issues中新增，谢谢你的贡献。
