### ISSUE TITLE
👨‍💻推荐身边的大佬朋友

### ISSUE THREAD

**Issue by Purple-sheep1022** [YSGStudyHards/DotNetGuide#15]
分享我认识的两位大佬，他们的网站
https://dotnet9.com/  https://www.coderbusy.com/ 

> 觉得不错，不妨收录下呗

**Comment by YSGStudyHards** [comment]
> 分享我认识的两位大佬，他们的网站 https://dotnet9.com/ https://www.coderbusy.com/
> 
> > 觉得不错，不妨收录下呗

嗯，这个建议不错，收录了，大家可以把自己心目中大佬贴出来，和大家共同学习进步。

**Comment by YSGStudyHards** [comment]
推荐身边大佬朋友已统一到这个issue中[https://github.com/YSGStudyHards/DotNetGuide/issues/8 ](https://github.com/YSGStudyHards/DotNetGuide/issues/8)
