### ISSUE TITLE
✍C#/.NET/.NET Core疑难问题解答

### ISSUE THREAD

**Issue by Yafeiml** [YSGStudyHards/DotNetGuide#22]
```c#
string[] names = { "yafei", "nan", "c#" };
while (enumerator.MoveNext())
{
    var name = (string) enumerator.Current;
    Console.WriteLine(name.GetType() + "   " + name.Length);
}

```
`var name = (string) enumerator.Current;`
这一句中的(string)具体作用是什么呢，已知的是不加这个name.Length是无效的？但是加不加这个getType得到的都是string，还有能说下这种用法叫什么吗？

**Comment by YSGStudyHards** [comment]
> ```cs
> string[] names = { "yafei", "nan", "c#" };
> while (enumerator.MoveNext())
> {
>     var name = (string) enumerator.Current;
>     Console.WriteLine(name.GetType() + "   " + name.Length);
> }
> ```
> 
> `var name = (string) enumerator.Current;` 这一句中的(string)具体作用是什么呢，已知的是不加这个name.Length是无效的？但是加不加这个getType得到的都是string，还有能说下这种用法叫什么吗？

关于(string)的作用，其实就是一种类型的[显式转换](https://learn.microsoft.com/zh-cn/dotnet/csharp/programming-guide/types/casting-and-type-conversions)，因为C#中var是一种匿名类型，编译器无法直接推断出name变量的类型，假如你把var替换成string就不需要使用这个显式转换了。

**Comment by Yafeiml** [comment]
> 关于(string)的作用，其实就是一种类型的[显式转换](https://learn.microsoft.com/zh-cn/dotnet/csharp/programming-guide/types/casting-and-type-conversions)，因为C#中var是一种匿名类型，编译器无法直接推断出name变量的类型，假如你把var替换成string就不需要使用这个显式转换了。

string name = enumerator.Current; 这样的话程序会报错，同样提示需要添加显示转换，不过明白了(string)属于显示转换，但是有区别于ToString()，感谢。
