### ISSUE TITLE
Xmtool常用工具库

### ISSUE THREAD

**Issue by softwaiter** [YSGStudyHards/DotNetGuide#28]
[Xmtool常用工具类库](https://github.com/softwaiter/Xmtool)

Xmtool是一个基于.NetCore框架的常用功能集成工具类库，目的是做成一个像Java语言中的Hutool类似的工具库，将和具体业务逻辑无关的常用功能和方法进行抽象、封装，集成到一个类库中，方便使用维护，提升开发效率。目前提供了正则表达式常用判断、日期时间常用方法、XML快速遍历、动态扩展对象、图片验证码生成、阿里/腾讯短信发送、发送邮件、Json配置文件解析、加密解密等等，持续集成中...

**Comment by YSGStudyHards** [comment]
谢谢分享，已经在这里面看到了 #11
