### ISSUE TITLE
🏷️C#/.NET/.NET Core推荐博文or博客or博主（汇总，大家有自己的博客可以到此记录，方便查阅）

### ISSUE THREAD

**Issue by lindexi** [YSGStudyHards/DotNetGuide#3]
https://blog.lindexi.com

https://lindexi.blog.csdn.net/

**Comment by YSGStudyHards** [comment]
很棒，解决把大佬的这个Issues作为一个专栏，归纳到.NET优秀博客中。

**Comment by YSGStudyHards** [comment]
很棒，解决把大佬的这个Issues作为一个专栏，归纳到.NET优秀博客中。

**Comment by YSGStudyHards** [comment]
> https://blog.lindexi.com
> 
> https://lindexi.blog.csdn.net/

你好，感谢你的推荐，已将您的博客地址归纳到了C#/.NET/.NET Core推荐博文or博客or博主issues推荐栏中，详细地址：[https://github.com/YSGStudyHards/DotNetGuide/issues/4](https://github.com/YSGStudyHards/DotNetGuide/issues/4)
