### ISSUE TITLE
API本地发布

### ISSUE THREAD

**Issue by zj1312114390** [YSGStudyHards/DotNetGuide#34]
![image](https://github.com/YSGStudyHards/DotNetGuide/assets/110399274/deb68a0a-ae24-4625-8a73-e85580abf19d)
本地发布的时候选择文件夹，然后选择完路径点击完成时没反应了，之前可以发布到本地，分盘后重新装了VS2019就出现这个问题了，请问怎么办？

**Comment by YSGStudyHards** [comment]
1. 重新选择文件夹位置发布
2. 使用dotnet publish命令发布：详情看这里https://learn.microsoft.com/zh-cn/dotnet/core/tools/dotnet-publish
有问题可以在这里面提https://github.com/YSGStudyHards/DotNetGuide/issues/23 我看到会解答，不用单独提Issues
